### ISSUE TITLE
Certain cards would trigger an Invalid search error

### ISSUE THREAD

**Issue by rkarabut** [ThoreBor/CC-CEDICT-for-Anki#31] opened 2022-07-06 09:30 UTC
Entries such as 是否 or 回合 would trigger this exception:

![image](https://user-images.githubusercontent.com/2141440/177519041-492bd15c-2888-4811-9ccc-913216557979.png)

**Comment by ThoreBor** [comment] 2022-07-18 17:05
Thanks for letting me know

**Comment by sykul** [comment] 2022-09-21 19:16
These words also trigger the same error for me as described in #34

**Comment by sykul** [comment] 2022-09-22 17:23
I'm going to close #34 because it seems to be a duplicate of this. I will paste the content into this post.

> The word I'm trying to add: 同归于尽 (although this has happened before, I just didn't 
> bother to report it)
> My action: search for the word, click on it, click 'Add card(s)'
> Expected behaviour: The word is added to my notes (it works for 99.9% of words still)
> Actual behaviour: I get this error message:
> 
>     Error
>     An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
>     If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
>     When you've discovered the add-on that is causing the problem, please report the issue to the add-on author.
>     Debug info:
>     Anki 2.1.54 (b6a7760c) Python 3.9.10 Qt 6.3.1 PyQt 6.3.1
>     Platform: Linux
>     Flags: frz=True ao=True sv=3
>     Add-ons, last update check: 2022-09-21 09:39:31
>     Add-ons possibly involved: ⁨CC-CEDICT for Anki Chinese dictionary⁩
>     Caught exception:
>     Traceback (most recent call last):
>     File "/home/lk/.local/share/Anki2/addons21/418828045/cedict/main.py", line 382, in init_add
>     self.add_note([simp, trad, pinyin, english], input_type, tags)
>     File "/home/lk/.local/share/Anki2/addons21/418828045/cedict/main.py", line 329, in add_note
>     note_ids_english = col.find_notes("{}:{}".format(english_field_name, english))
>     File "anki.collection", line 646, in find_notes
>     File "anki._backend.generated", line 1477, in search_notes
>     File "anki._backend", line 146, in _run_command
>     anki.errors.SearchError:
> 
>     Invalid search: ⁨an or was found but it is not connecting two search terms. If you want to search for the word itself, wrap it in double quotes: "or".⁩

P.S. This word also triggers the error: 小数

**Closed as completed** 2023-10-27 19:09 UTC
Labels: bug
